### ISSUE TITLE
Add more quantitative data to the code usage SDR

### ISSUE THREAD

**Issue by milanwiedemann** [opensafely/uom_pregnancy_tx_pathways#198]
Add something like the following to the report/app:

- Quantitative sentences eg. of the X codes in the [delivery] codelist: X are driving 80% of volume in the latest year. X of these codes are in the top volume since 2011, however XX codes are only present from 2018 onwards. [maybe investigate a little - this coincides with new measures/codes being implemented/change to NICE guidelines]
- Top 10 codes table for each codelist in latest year and over whole period separately (is there a difference in the top 10?)
- Codes with the most variation over the time period. Focus on codes with variation which are contributing to high volumes (>5% codes) + change drastically (more than 30% change across a year, and separately, across the period). Use cut off of 5 variations per codelist - if there are more than that, tweak parameters to get fewer.

**Comment by rose-higgins** [comment]
@milanwiedemann  to check if all changes are merged into repo

**Comment by viv3ckj** [comment]
@milanwiedemann to update

**Comment by milanwiedemann** [comment]
done
